query allPopular {
  uslugi{
    Usluga {
      popularna
      nazwa
      opis
      czas_trwania
      cena
    }
  }
  lekcje {
    usluga {
      popularna
      nazwa
      opis
      czas_trwania
      cena
    }
  }
  brwi {
    usluga {
      popularna
      nazwa
      opis
      czas_trwania
      cena
    }
  }
  pakiets(where:{popularna:true}) {
    nazwa
    czas_trwania
    cena
    uslugi {
      element
    }
  }
}
