query allPopular {
  uslugi{
    Usluga(where:{popularna:true}) {
      nazwa
      opis
      czas_trwania
      cena
    }
  }
  lekcje {
    Usluga(where:{popularna:true}) {
      nazwa
      opis
      czas_trwania
      cena
    }
  }
  pakiets(where:{popularna:true}) {
    nazwa
    czas_trwania
    cena
    uslugi {
      element
    }
  }
}
